### ISSUE TITLE
Building issues (debian/control) and CmakeLists.txt 

### ISSUE THREAD

**Issue by asilenkov** [reverbrain/rift#2]
1. Latest Rift v0.6.9 wants "elliptics-dev (>= 2.24.15.1), elliptics-dev (<< 2.25.0.0)" in build-depends. However latest tag of elliptics is 2.25.1.0. Is it invented that we want <<2.25.0.0 or its just a typo? BTW Rift v0.6.8 don't have this dependency. 
2. CMakeLists.txt +20 declare "find_package(Elliptics 2.24 REQUIRED)". However latest tag of elliptics is 2.25.1.0.

I've just cleaned this up a little and it seems to work fine.

**Comment by bioothod** [comment]
You should use elliptics-2.25 branch or use packages from http://repo.reverbrain.com

Master branch is intended to be compiled against 2.24 LTS elliptics releases

**Comment by asilenkov** [comment]
Yep, a little bit confusing. Elliptics points to 4 branches:
- cocaine-evolution -> v2.24.14.26
- lts -> v2.24.15.10
- master -> v2.25.1.1
- stable -> v2.20.6.11
  And alot of tags -> 2.25.1.0, 2.25.0.0 so on. 

I've taken latest tags or branches (if available) of all projects and build it together with success except Rift. 
cocaine-core_0.11.2.2.dsc
cocaine-framework-native_0.11.0.3.dsc
cocaine-framework-python_0.11.1.1.dsc
eblob_0.21.29.dsc
elliptics_2.25.1.1.dsc
grape_0.6.19.dsc
rift_0.6.9.dsc
swarm_0.6.1.3.dsc

Sometimes package is branched sometimes not. It is not clear how to build it at least for me )))) It could be more convenient to have some generic tag (or better branch) for all projects intended to build together. 
ok TY, closed.

**Comment by bioothod** [comment]
Rift is a bit ahead now, it uses new versioning system like rift 2.25.0.6.10, where 2.25 is elliptics major version
