### ISSUE TITLE
Metadata groups RIFT got Failed to access.

### ISSUE THREAD

**Issue by asilenkov** [reverbrain/rift#3]
So I have working cluster with 2 nodes in group 2. Everything works with dnet_ioclient, adding/removing content so on. Now Rift time. Basically can't figure out how to inject it to working cluster. 
user@storage-11:/etc/elliptics# cat rift.json 
{
    "endpoints": [
        "0.0.0.0:8080"
    ],
    "backlog": 1024,
    "threads": 4,
    "buffer_size": 65536,
    "logger": {
        "file": "/dev/stderr",
        "level": 20
    },
    "daemon": {
        "fork": false,
        "uid": 1000
    },
    "monitor-port": 20000,
    "application": {
        "remotes": [
            "host2:1025:2"
        ],
        "groups": [
            2
        ],
        "metadata-groups": [
            2
        ],
        "cache": {
            "name": "cache"
        },
    "noauth" : "forbidden",
        "bucket": {},
        "redirect-port": 8080,
        "https": true
    }
}

Now bucket
user@storage-11:~#rift_bucket_ctl --remote host2:1025:2 --bucket Testbucket --metadata-groups 2 --noauth all --data-groups 2
Successfully written bucket metadata
Metadata info:
  bucket: Testbucket
  token: 
  data groups: 2
  flags: 0x2
  maximum record size: 0
  maximum number of keys: 0
  metadata stored in the following groups: 2

metadata-groups seems not working for me:
Failed to access groups file: 2:c6c4b6b7ad45...52e3cdf7e9b7: Failed to process READ command: No such file or directory: -2
/ping got 200
all other requests got 400

Monitoring shows me something like
user@storage-11:~# echo i | netcat localhost 20000
{
    "connections": 1,
    "active-connections": 0,
    "application": {}
}

Am I missing something? "noauth" : "forbidden" is wrong here or what?

**Comment by bioothod** [comment]
metadata-groups are groups where bucket info is stored, i.e. that data you wrote using rift_bucket_ctl

data-groups is where data keys live.

How do you read data through the rift?
It should be something like: curl "http://host1:8080/get?name=some-key&namespace=Testbucket"

**Comment by asilenkov** [comment]
Quite confusing. Tried to upload some and finally got it to work with
curl -v -X POST -d @debian.iso "http://host1:8080/upload-big?name=debian.iso&namespace=Testbucket"

However http://doc.reverbrain.com/rift:rift "URI handlers" said about "-ns=" parameter, not "namespace=" But sadly it is not working. 
curl -v -X POST -d @debian.iso "http://host1:8080/upload-big?name=debian.iso&ns=Testbucket" got 400. TY closed.

**Comment by bioothod** [comment]
Yup, doc is a bit outdated, I will fix it, thank you
