### ISSUE TITLE
OOM trying to get key list from rift

### ISSUE THREAD

**Issue by asilenkov** [reverbrain/rift#5]
The same cluster - 2 nodes 55Gb data, don't' know exact number of keys but it's like 10000. Tried to get curl like in example "http://example.com/list?namespace=testns&name="
But suddenly oom killed. Python script didn't work too.

```
        total       used       free     shared    buffers     cached
```

Mem:      32993092    8596040   24397052          0      11164    8168084
-/+ buffers/cache:     416792   32576300
Swap:      7811064      62496    7748568

[ 7406.933549] Killed process 6563 (dnet-io_pool)
[ 7406.937250] dnet-net_pool invoked oom-killer: gfp_mask=0x201da, order=0, oom_adj=0
[ 7406.937254] dnet-net_pool cpuset=/ mems_allowed=0-1
[ 7406.937257] Pid: 29645, comm: dnet-net_pool Not tainted 2.6.32-5-amd64 #1
[ 7406.937259] Call Trace:
[ 7406.937267]  [<ffffffff810b6714>] ? oom_kill_process+0x7f/0x23f
[ 7406.937271]  [<ffffffff8106bdee>] ? timekeeping_get_ns+0xe/0x2e
[ 7406.937273]  [<ffffffff810b6c38>] ? __out_of_memory+0x12a/0x141
[ 7406.937275]  [<ffffffff810b6d8f>] ? out_of_memory+0x140/0x172
[ 7406.937279]  [<ffffffff810baaf4>] ? __alloc_pages_nodemask+0x4ec/0x5fc
[ 7406.937282]  [<ffffffff810bc05d>] ? __do_page_cache_readahead+0x9b/0x1b4
[ 7406.937285]  [<ffffffff810bc192>] ? ra_submit+0x1c/0x20
[ 7406.937287]  [<ffffffff810b4e5f>] ? filemap_fault+0x17d/0x2f6
[ 7406.937291]  [<ffffffff810cae2a>] ? __do_fault+0x54/0x3c3
[ 7406.937296]  [<ffffffff8105aaa4>] ? lock_timer_base+0x26/0x4b
[ 7406.937298]  [<ffffffff8105ab2c>] ? try_to_del_timer_sync+0x63/0x6c
[ 7406.937301]  [<ffffffff810cd17e>] ? handle_mm_fault+0x3b8/0x80f
[ 7406.937305]  [<ffffffff8111a1d3>] ? sys_epoll_wait+0x23c/0x254
[ 7406.937310]  [<ffffffff813001a6>] ? do_page_fault+0x2e0/0x2fc
[ 7406.937313]  [<ffffffff812fe045>] ? page_fault+0x25/0x30
[ 7406.937314] Mem-Info:
[ 7406.937315] Node 0 DMA per-cpu:
[ 7406.937318] CPU    0: hi:    0, btch:   1 usd:   0
[ 7406.937319] CPU    1: hi:    0, btch:   1 usd:   0
[ 7406.937321] CPU    2: hi:    0, btch:   1 usd:   0
[ 7406.937322] CPU    3: hi:    0, btch:   1 usd:   0
[ 7406.937324] CPU    4: hi:    0, btch:   1 usd:   0
[ 7406.937325] CPU    5: hi:    0, btch:   1 usd:   0
[ 7406.937327] CPU    6: hi:    0, btch:   1 usd:   0
[ 7406.937328] CPU    7: hi:    0, btch:   1 usd:   0
[ 7406.937329] Node 0 DMA32 per-cpu:
[ 7406.937331] CPU    0: hi:  186, btch:  31 usd:   0
[ 7406.937333] CPU    1: hi:  186, btch:  31 usd:   0
[ 7406.937334] CPU    2: hi:  186, btch:  31 usd:   0
[ 7406.937336] CPU    3: hi:  186, btch:  31 usd:   0
[ 7406.937337] CPU    4: hi:  186, btch:  31 usd:   0
[ 7406.937339] CPU    5: hi:  186, btch:  31 usd:   0
[ 7406.937340] CPU    6: hi:  186, btch:  31 usd:   0
[ 7406.937341] CPU    7: hi:  186, btch:  31 usd:   0
[ 7406.937342] Node 0 Normal per-cpu:
[ 7406.937344] CPU    0: hi:  186, btch:  31 usd: 100
[ 7406.937346] CPU    1: hi:  186, btch:  31 usd:   0
[ 7406.937347] CPU    2: hi:  186, btch:  31 usd:  22
[ 7406.937349] CPU    3: hi:  186, btch:  31 usd:   7
[ 7406.937350] CPU    4: hi:  186, btch:  31 usd:   0
[ 7406.937351] CPU    5: hi:  186, btch:  31 usd:   0
[ 7406.937353] CPU    6: hi:  186, btch:  31 usd:   0
[ 7406.937354] CPU    7: hi:  186, btch:  31 usd:   0
[ 7406.937356] Node 1 Normal per-cpu:
[ 7406.937358] CPU    0: hi:  186, btch:  31 usd:   9
[ 7406.937359] CPU    1: hi:  186, btch:  31 usd:   0
[ 7406.937360] CPU    2: hi:  186, btch:  31 usd:   0
[ 7406.937362] CPU    3: hi:  186, btch:  31 usd:   0
[ 7406.937363] CPU    4: hi:  186, btch:  31 usd:  20
[ 7406.937365] CPU    5: hi:  186, btch:  31 usd:  28
[ 7406.937366] CPU    6: hi:  186, btch:  31 usd:  13
[ 7406.937367] CPU    7: hi:  186, btch:  31 usd:  27
[ 7406.937371] active_anon:7445506 inactive_anon:724719 isolated_anon:0
[ 7406.937372]  active_file:76 inactive_file:0 isolated_file:0
[ 7406.937373]  unevictable:925 dirty:0 writeback:970 unstable:0
[ 7406.937373]  free:23656 slab_reclaimable:1744 slab_unreclaimable:9841
[ 7406.937374]  mapped:707 shmem:7 pagetables:20969 bounce:0
[ 7406.937376] Node 0 DMA free:15840kB min:8kB low:8kB high:12kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15256kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:0kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
[ 7406.937384] lowmem_reserve[]: 0 1948 16088 16088
[ 7406.937387] Node 0 DMA32 free:57792kB min:1388kB low:1732kB high:2080kB active_anon:1263360kB inactive_anon:420884kB active_file:12kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:1995432kB mlocked:0kB dirty:0kB writeback:0kB mapped:4kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:44kB kernel_stack:16kB pagetables:5256kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:128 all_unreclaimable? yes
[ 7406.937395] lowmem_reserve[]: 0 0 14140 14140
[ 7406.937398] Node 0 Normal free:9792kB min:10072kB low:12588kB high:15108kB active_anon:13335368kB inactive_anon:1212640kB active_file:128kB inactive_file:4kB unevictable:3172kB isolated(anon):0kB isolated(file):0kB present:14479360kB mlocked:3172kB dirty:0kB writeback:1164kB mapped:2256kB shmem:12kB slab_reclaimable:4096kB slab_unreclaimable:33132kB kernel_stack:2104kB pagetables:37736kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? no
[ 7406.937406] lowmem_reserve[]: 0 0 0 0
[ 7406.937409] Node 1 Normal free:11200kB min:11512kB low:14388kB high:17268kB active_anon:15183296kB inactive_anon:1265352kB active_file:164kB inactive_file:0kB unevictable:528kB isolated(anon):0kB isolated(file):0kB present:16547840kB mlocked:528kB dirty:0kB writeback:2716kB mapped:568kB shmem:16kB slab_reclaimable:2880kB slab_unreclaimable:6188kB kernel_stack:264kB pagetables:40884kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? no
[ 7406.937417] lowmem_reserve[]: 0 0 0 0
[ 7406.937419] Node 0 DMA: 2_4kB 1_8kB 1_16kB 2_32kB 2_64kB 0_128kB 1_256kB 0_512kB 1_1024kB 1_2048kB 3_4096kB = 15840kB
[ 7406.937426] Node 0 DMA32: 32_4kB 99_8kB 84_16kB 59_32kB 48_64kB 26_128kB 21_256kB 16_512kB 11_1024kB 9_2048kB 1_4096kB = 57912kB
[ 7406.937432] Node 0 Normal: 1309_4kB 4_8kB 11_16kB 10_32kB 18_64kB 3_128kB 0_256kB 1_512kB 0_1024kB 1_2048kB 0_4096kB = 9860kB
[ 7406.937438] Node 1 Normal: 200_4kB 133_8kB 66_16kB 47_32kB 8_64kB 1_128kB 1_256kB 1_512kB 1_1024kB 0_2048kB 1_4096kB = 10952kB
[ 7406.937445] 7308 total pagecache pages
[ 7406.937446] 6859 pages in swap cache
[ 7406.937447] Swap cache stats: add 1956517, delete 1949658, find 237/532
[ 7406.937449] Free swap  = 0kB
[ 7406.937450] Total swap = 7811064kB
[ 7407.016405] 8388592 pages RAM
[ 7407.016407] 140319 pages reserved
[ 7407.016408] 5725 pages shared
[ 7407.016409] 8222152 pages non-shared
[ 7407.016443] Killed process 6565 (dnet-net_pool)

Not sure what is wrong, server is hosting only elliptics installation and hardly do any load.

**Comment by bioothod** [comment]
I'm trying to reproduce it locally, in a meantime can you please provide blob's data.stat file on both nodes as well as server and rift log with 3 or higher log level during listing command execution?

**Comment by asilenkov** [comment]
I've just mailed all related logs to info@reverbrain.com. Sadly second node didn't survive the tests so we have logs only from 1 node.

**Comment by bioothod** [comment]
As we discussed in private mails, it was server's environment setup issue, so I close it for now
